"""
SITL parameter file writer.

Converts identified FDM parameters to ArduPilot SITL-compatible .parm format.
"""

from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime
import numpy as np


def convert_to_sitl_params(params: Dict[str, float], frame_config: Optional[Dict] = None) -> Dict[str, float]:
    """
    Convert identified FDM parameters to SITL parameter names.

    Args:
        params: Dictionary of identified parameters (mass, Ixx, Iyy, Izz, kT, kQ, tau_motor, c_drag, etc.)
        frame_config: Optional frame configuration dictionary

    Returns:
        Dictionary mapping SITL parameter names to values
    """
    sitl_params = {}

    # Mass
    if 'mass' in params:
        sitl_params['SIM_MASS'] = params['mass']

    # Moments of inertia
    if 'Ixx' in params:
        sitl_params['SIM_MOI_X'] = params['Ixx']
    if 'Iyy' in params:
        sitl_params['SIM_MOI_Y'] = params['Iyy']
    if 'Izz' in params:
        sitl_params['SIM_MOI_Z'] = params['Izz']

    # Thrust parameters
    # SITL uses thrust max (N) and expo
    if 'kT' in params and frame_config:
        # Estimate max thrust assuming max motor RPM
        n_motors = len(frame_config.get('motor_positions', []))
        max_rpm = params.get('max_rpm', 10000)  # rad/s
        max_thrust_per_motor = params['kT'] * (max_rpm ** 2)
        sitl_params['SIM_THST_MAX'] = max_thrust_per_motor * n_motors

    # Motor drag coefficient
    if 'c_drag' in params:
        sitl_params['SIM_MOT_DRAG'] = params['c_drag']

    # ESC time constant
    if 'tau_motor' in params:
        sitl_params['SIM_ESC_TCONST'] = params['tau_motor']

    # Thrust expo (nonlinearity) - if we have polynomial coefficients
    if 'pwm_to_omega_poly' in params and len(params['pwm_to_omega_poly']) > 1:
        poly = params['pwm_to_omega_poly']
        # Simple heuristic: expo represents quadratic term relative to linear
        if len(poly) >= 3 and poly[1] != 0:
            expo = abs(poly[2] / poly[1])
            sitl_params['SIM_THST_EXPO'] = np.clip(expo, 0.0, 1.0)
        else:
            sitl_params['SIM_THST_EXPO'] = 0.5  # default

    # Wind defaults (not identified)
    sitl_params['SIM_WIND_SPD'] = 0.0
    sitl_params['SIM_WIND_DIR'] = 0.0

    return sitl_params


def write_parm_file(
    output_path: Path,
    sitl_params: Dict[str, float],
    metadata: Optional[Dict[str, Any]] = None
) -> None:
    """
    Write SITL parameters to .parm file.

    Args:
        output_path: Path to output .parm file
        sitl_params: Dictionary of SITL parameters
        metadata: Optional metadata to include in header comments
    """
    output_path = Path(output_path)

    lines = []

    # Header
    lines.append("# Generated by ardupilot-sysid v0.1.0")
    lines.append(f"# Generated: {datetime.now().isoformat()}")

    if metadata:
        if 'log_file' in metadata:
            lines.append(f"# Source log: {metadata['log_file']}")
        if 'frame_type' in metadata:
            lines.append(f"# Frame type: {metadata['frame_type']}")
        if 'validation_rmse' in metadata:
            val = metadata['validation_rmse']
            if isinstance(val, dict):
                rmse_str = ', '.join([f"{k}={v:.2f}" for k, v in val.items()])
                lines.append(f"# Validation RMSE: {rmse_str}")

    lines.append("")

    # Parameters (sorted for consistency)
    for param_name in sorted(sitl_params.keys()):
        value = sitl_params[param_name]
        # Format with appropriate precision
        if isinstance(value, float):
            if abs(value) < 0.001:
                lines.append(f"{param_name},{value:.6f}")
            elif abs(value) < 1.0:
                lines.append(f"{param_name},{value:.4f}")
            else:
                lines.append(f"{param_name},{value:.3f}")
        else:
            lines.append(f"{param_name},{value}")

    # Write to file
    output_path.write_text('\n'.join(lines) + '\n')
