"""Tests for output generation module."""

import json
import numpy as np
import pytest
from pathlib import Path
import tempfile

from src.output.parm_writer import (
    convert_to_sitl_params,
    write_parm_file
)
from src.output.report import (
    generate_json_report,
    generate_text_report
)


class TestConvertToSITLParams:
    """Test conversion from FDM parameters to SITL parameters."""

    def test_mass_conversion(self):
        """Test mass parameter conversion."""
        params = {'mass': 1.5}

        sitl = convert_to_sitl_params(params)

        assert 'SIM_MASS' in sitl
        assert sitl['SIM_MASS'] == 1.5

    def test_inertia_conversion(self):
        """Test inertia tensor conversion."""
        params = {'inertia': np.array([0.01, 0.02, 0.03])}

        sitl = convert_to_sitl_params(params)

        assert 'SIM_MOI_X' in sitl
        assert 'SIM_MOI_Y' in sitl
        assert 'SIM_MOI_Z' in sitl
        assert sitl['SIM_MOI_X'] == 0.01
        assert sitl['SIM_MOI_Y'] == 0.02
        assert sitl['SIM_MOI_Z'] == 0.03

    def test_thrust_conversion(self):
        """Test thrust coefficient to max thrust conversion."""
        params = {
            'kT': 1.5e-5,
            'pwm_to_omega_poly': np.array([0.0, 1000.0])  # Linear: ω = 1000 * PWM
        }

        sitl = convert_to_sitl_params(params)

        assert 'SIM_THST_MAX' in sitl
        assert 'SIM_THST_EXPO' in sitl

        # Total thrust = 4 motors * kT * omega_max^2
        expected_max = 4 * 1.5e-5 * 1000.0**2
        assert sitl['SIM_THST_MAX'] == pytest.approx(expected_max)

    def test_motor_time_constant(self):
        """Test motor time constant conversion."""
        params = {'tau_motor': 0.05}

        sitl = convert_to_sitl_params(params)

        assert 'SIM_ESC_TCONST' in sitl
        assert sitl['SIM_ESC_TCONST'] == 0.05

    def test_rotational_drag(self):
        """Test rotational drag conversion."""
        params = {'c_drag': 0.001}

        sitl = convert_to_sitl_params(params)

        assert 'SIM_MOT_DRAG' in sitl
        assert sitl['SIM_MOT_DRAG'] == 0.001

    def test_complete_conversion(self):
        """Test conversion with all parameters."""
        params = {
            'mass': 1.2,
            'inertia': np.array([0.015, 0.018, 0.025]),
            'kT': 1.2e-5,
            'pwm_to_omega_poly': np.array([0.0, 900.0]),
            'tau_motor': 0.04,
            'c_drag': 0.0008
        }

        sitl = convert_to_sitl_params(params)

        # Expect 8 parameters: MASS, MOI_X, MOI_Y, MOI_Z, THST_MAX, THST_EXPO, ESC_TCONST, MOT_DRAG
        assert len(sitl) == 8
        assert all(isinstance(v, float) for v in sitl.values())

    def test_missing_parameters(self):
        """Test graceful handling of missing parameters."""
        params = {'mass': 1.0}  # Only mass

        sitl = convert_to_sitl_params(params)

        assert 'SIM_MASS' in sitl
        assert 'SIM_MOI_X' not in sitl  # Not present


class TestWriteParmFile:
    """Test SITL parameter file writing."""

    def test_basic_file_write(self):
        """Test basic .parm file creation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'test.parm'

            sitl_params = {
                'SIM_MASS': 1.5,
                'SIM_MOI_X': 0.01,
                'SIM_MOI_Y': 0.02
            }

            write_parm_file(str(output_path), sitl_params)

            assert output_path.exists()

            # Read and verify content
            content = output_path.read_text()
            assert 'SIM_MASS,1.5' in content
            assert 'SIM_MOI_X,0.01' in content
            assert 'SIM_MOI_Y,0.02' in content

    def test_header_comments(self):
        """Test that header comments are included."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'test.parm'

            sitl_params = {'SIM_MASS': 1.0}

            write_parm_file(str(output_path), sitl_params)

            content = output_path.read_text()
            assert '# Generated by ardupilot-sysid' in content
            assert '# Generation date:' in content

    def test_metadata_in_header(self):
        """Test metadata inclusion in header."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'test.parm'

            sitl_params = {'SIM_MASS': 1.0}
            metadata = {
                'log_file': 'flight001.bin',
                'frame_type': 'quad_x',
                'validation_rmse': {
                    'roll_deg': 1.2,
                    'pitch_deg': 1.5,
                    'yaw_deg': 2.0
                }
            }

            write_parm_file(str(output_path), sitl_params, metadata)

            content = output_path.read_text()
            assert 'flight001.bin' in content
            assert 'quad_x' in content
            assert 'roll=1.2' in content
            assert 'pitch=1.5' in content
            assert 'yaw=2.0' in content

    def test_sorted_parameters(self):
        """Test that parameters are sorted alphabetically."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'test.parm'

            sitl_params = {
                'SIM_MOI_Z': 0.03,
                'SIM_MASS': 1.0,
                'SIM_MOI_X': 0.01
            }

            write_parm_file(str(output_path), sitl_params)

            content = output_path.read_text()
            lines = [l for l in content.split('\n') if not l.startswith('#') and l.strip()]

            assert lines[0].startswith('SIM_MASS')
            assert lines[1].startswith('SIM_MOI_X')
            assert lines[2].startswith('SIM_MOI_Z')

    def test_scientific_notation(self):
        """Test proper formatting of small numbers."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'test.parm'

            sitl_params = {
                'SIM_MOT_DRAG': 0.0001234,
                'SIM_MASS': 1500.0
            }

            write_parm_file(str(output_path), sitl_params)

            content = output_path.read_text()
            # Check that numbers are properly formatted (6 significant figures)
            assert 'SIM_MOT_DRAG' in content
            assert 'SIM_MASS' in content


class TestGenerateJSONReport:
    """Test JSON report generation."""

    def test_basic_report_structure(self):
        """Test basic JSON report structure."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'report.json'

            params = {'mass': 1.5, 'inertia': [0.01, 0.02, 0.03]}
            cis = {'mass': (1.4, 1.6)}
            excitation = {'mass': {'score': 0.95, 'excited': True}}
            validation = {
                'attitude': {'roll_deg': 1.0, 'pitch_deg': 1.2, 'yaw_deg': 1.5},
                'velocity': {'v_total': 0.05}
            }
            metadata = {
                'log_file': 'test.bin',
                'frame_type': 'quad_x',
                'flight_duration_s': 120.0
            }

            generate_json_report(
                params, cis, excitation, validation, metadata, str(output_path)
            )

            assert output_path.exists()

            # Parse and verify
            with open(output_path) as f:
                report = json.load(f)

            assert 'metadata' in report
            assert 'identified_parameters' in report
            assert 'excitation_scores' in report
            assert 'warnings' in report
            assert 'validation' in report

    def test_parameter_with_confidence_intervals(self):
        """Test parameter entries with confidence intervals."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'report.json'

            params = {'mass': 1.5, 'kT': 1.2e-5}
            cis = {'mass': (1.4, 1.6), 'kT': (1.1e-5, 1.3e-5)}
            excitation = {}
            validation = {}
            metadata = {}

            generate_json_report(
                params, cis, excitation, validation, metadata, str(output_path)
            )

            with open(output_path) as f:
                report = json.load(f)

            assert 'mass' in report['identified_parameters']
            assert 'value' in report['identified_parameters']['mass']
            assert 'ci_95' in report['identified_parameters']['mass']
            assert report['identified_parameters']['mass']['ci_95'] == [1.4, 1.6]

    def test_array_parameter_conversion(self):
        """Test that array parameters are converted to lists."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'report.json'

            params = {'inertia': np.array([0.01, 0.02, 0.03])}
            cis = {}
            excitation = {}
            validation = {}
            metadata = {}

            generate_json_report(
                params, cis, excitation, validation, metadata, str(output_path)
            )

            with open(output_path) as f:
                report = json.load(f)

            inertia_value = report['identified_parameters']['inertia']['value']
            assert isinstance(inertia_value, list)
            assert len(inertia_value) == 3

    def test_warnings_generation(self):
        """Test automatic warning generation for poorly excited parameters."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'report.json'

            params = {'mass': 1.5}
            cis = {}
            excitation = {
                'mass': {'score': 0.3, 'excited': False}
            }
            validation = {}
            metadata = {}

            generate_json_report(
                params, cis, excitation, validation, metadata, str(output_path)
            )

            with open(output_path) as f:
                report = json.load(f)

            assert len(report['warnings']) > 0
            assert 'mass' in report['warnings'][0]
            assert 'poorly excited' in report['warnings'][0]


class TestGenerateTextReport:
    """Test text report generation."""

    def test_basic_text_report(self):
        """Test basic text report generation."""
        params = {'mass': 1.5, 'kT': 1.2e-5}
        cis = {'mass': (1.4, 1.6)}
        validation = {
            'attitude': {'roll_deg': 1.0, 'pitch_deg': 1.2, 'yaw_deg': 1.5},
            'velocity': {'v_total': 0.05}
        }

        report = generate_text_report(params, cis, validation)

        assert 'ARDUPILOT SITL PARAMETER IDENTIFICATION REPORT' in report
        assert 'mass' in report
        assert '1.5' in report
        assert 'Roll RMSE' in report
        # Format could be 1.0° or 1.00°
        assert '1.0' in report or '1.00' in report

    def test_file_output(self):
        """Test writing text report to file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / 'report.txt'

            params = {'mass': 1.5}
            cis = {}
            validation = {}

            report_text = generate_text_report(params, cis, validation, str(output_path))

            assert output_path.exists()
            assert output_path.read_text() == report_text

    def test_confidence_interval_formatting(self):
        """Test proper formatting of confidence intervals."""
        params = {'mass': 1.5}
        cis = {'mass': (1.4, 1.6)}
        validation = {}

        report = generate_text_report(params, cis, validation)

        assert '[1.4' in report
        assert '1.6]' in report

    def test_validation_metrics_formatting(self):
        """Test proper formatting of validation metrics."""
        params = {}
        cis = {}
        validation = {
            'attitude': {
                'roll_deg': 1.234,
                'pitch_deg': 2.345,
                'yaw_deg': 3.456
            },
            'velocity': {
                'v_total': 0.0567
            }
        }

        report = generate_text_report(params, cis, validation)

        # Check proper decimal formatting
        assert '1.23°' in report or '1.234°' in report
        assert '0.057' in report or '0.0567' in report


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
