from typing import Dict
from datetime import datetime
from pathlib import Path


def convert_to_sitl_params(params: Dict) -> Dict[str, float]:
    """
    Convert identified FDM parameters to ArduPilot SITL parameter names.

    Parameter mapping:
        mass_kg → SIM_MASS
        Ixx, Iyy, Izz → SIM_MOI_X, SIM_MOI_Y, SIM_MOI_Z
        kT → SIM_THST_MAX (needs conversion)
        tau_motor → SIM_ESC_TCONST
        c_drag → SIM_MOT_DRAG

    Args:
        params: Dict of identified parameters

    Returns:
        Dict mapping SITL parameter name → value
    """
    sitl_params = {}

    # Mass
    if 'mass' in params:
        sitl_params['SIM_MASS'] = float(params['mass'])

    # Moments of inertia
    if 'inertia' in params:
        inertia = params['inertia']
        sitl_params['SIM_MOI_X'] = float(inertia[0])
        sitl_params['SIM_MOI_Y'] = float(inertia[1])
        sitl_params['SIM_MOI_Z'] = float(inertia[2])

    # Thrust coefficient → max thrust
    # SIM_THST_MAX is total thrust at full throttle (N)
    # kT is per-motor, so multiply by number of motors and max RPM²
    if 'kT' in params and 'pwm_to_omega_poly' in params:
        kT = float(params['kT'])
        poly = params['pwm_to_omega_poly']
        omega_max = float(poly[1])  # Assuming linear: ω = a1 * PWM at PWM=1

        # Total thrust = n_motors * kT * omega_max²
        # Assuming quad (4 motors) - would need frame info for generality
        n_motors = 4
        sitl_params['SIM_THST_MAX'] = kT * omega_max**2 * n_motors

        # Thrust expo (0.5 = linear, higher = more exponential)
        # For polynomial fit, can estimate from a2/a1 ratio
        sitl_params['SIM_THST_EXPO'] = 0.5  # Default linear

    # Motor time constant
    if 'tau_motor' in params:
        sitl_params['SIM_ESC_TCONST'] = float(params['tau_motor'])

    # Rotational drag
    if 'c_drag' in params:
        sitl_params['SIM_MOT_DRAG'] = float(params['c_drag'])

    return sitl_params


def write_parm_file(
    output_path: str,
    sitl_params: Dict[str, float],
    metadata: Dict = None
) -> None:
    """
    Write ArduPilot SITL parameter file (.parm format).

    Format: PARAM_NAME,value\n (CSV-like, no spaces)

    Args:
        output_path: Path to output .parm file
        sitl_params: Dict of SITL parameters
        metadata: Optional metadata for header comments

    Example:
        >>> params_sitl = convert_to_sitl_params(params_identified)
        >>> write_parm_file('sitl_params.parm', params_sitl, metadata={'log': 'flight.bin'})
    """
    path = Path(output_path)

    with open(path, 'w') as f:
        # Header comments
        f.write(f"# Generated by ardupilot-sysid v0.1.0\n")
        f.write(f"# Generation date: {datetime.now().isoformat()}\n")

        if metadata:
            if 'log_file' in metadata:
                f.write(f"# Source log: {metadata['log_file']}\n")
            if 'frame_type' in metadata:
                f.write(f"# Vehicle: {metadata['frame_type']}\n")
            if 'validation_rmse' in metadata:
                rmse = metadata['validation_rmse']
                f.write(f"# Validation RMSE: roll={rmse.get('roll_deg', 0):.1f}° ")
                f.write(f"pitch={rmse.get('pitch_deg', 0):.1f}° ")
                f.write(f"yaw={rmse.get('yaw_deg', 0):.1f}°\n")

        f.write("#\n")

        # Parameters (sorted for consistency)
        for param_name in sorted(sitl_params.keys()):
            value = sitl_params[param_name]
            f.write(f"{param_name},{value:.6g}\n")

    print(f"✓ SITL parameters written to: {path}")
